name: Build

on: [push, pull_request]

jobs:
  assemble:
    name: Build debug APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Assemble APKs
      run: bash ./gradlew assemble --stacktrace
    - name: Create Debug APK artifiact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
  lint:
    name: Lint Debug
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Run lint
      run: bash ./gradlew lintDebug --stacktrace
    - name: Create report artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: lint-report
        path: app/build/reports/
